function _7 () {
    led.plot(0, 0)
    led.plot(0, 1)
    led.plot(1, 0)
    led.plot(1, 1)
    led.plot(4, 0)
    led.plot(4, 1)
    led.plot(3, 0)
    led.plot(3, 1)
    led.plot(0, 3)
    led.plot(1, 2)
    led.plot(2, 2)
    led.plot(3, 2)
    led.plot(4, 3)
}
function _2 () {
    led.plot(0, 0)
    led.plot(0, 1)
    led.plot(1, 0)
    led.plot(1, 1)
    led.plot(4, 0)
    led.plot(4, 1)
    led.plot(3, 0)
    led.plot(3, 1)
    led.plot(0, 3)
    led.plot(1, 4)
    led.plot(2, 4)
    led.plot(3, 4)
    led.plot(4, 3)
}
function _6 () {
    led.plot(0, 0)
    led.plot(0, 1)
    led.plot(1, 0)
    led.plot(1, 1)
    led.plot(4, 0)
    led.plot(4, 1)
    led.plot(3, 0)
    led.plot(3, 1)
    led.plot(0, 3)
    led.plot(1, 3)
    led.plot(2, 3)
    led.plot(3, 3)
    led.plot(4, 3)
}
input.onButtonPressed(Button.A, function () {
    while (true) {
        _1()
        basic.pause(slag)
        basic.clearScreen()
        _2()
        basic.pause(slag)
        basic.clearScreen()
        _3()
        basic.pause(slag)
        basic.clearScreen()
        _4()
        basic.pause(slag)
        basic.clearScreen()
        _5()
        basic.pause(slag)
        basic.clearScreen()
        _6()
        basic.pause(slag)
        basic.clearScreen()
        _7()
        basic.pause(slag)
        basic.clearScreen()
    }
})
function _5 () {
    led.plot(0, 1)
    led.plot(1, 1)
    led.plot(4, 0)
    led.plot(4, 1)
    led.plot(3, 0)
    led.plot(3, 1)
    led.plot(0, 3)
    led.plot(1, 4)
    led.plot(2, 4)
    led.plot(3, 4)
    led.plot(4, 3)
}
function _3 () {
    led.plot(0, 1)
    led.plot(1, 1)
    led.plot(4, 0)
    led.plot(4, 1)
    led.plot(3, 0)
    led.plot(3, 1)
    led.plot(0, 3)
    led.plot(1, 4)
    led.plot(2, 4)
    led.plot(3, 4)
    led.plot(4, 3)
}
function _4 () {
    led.plot(0, 0)
    led.plot(0, 1)
    led.plot(1, 0)
    led.plot(1, 1)
    led.plot(4, 0)
    led.plot(4, 1)
    led.plot(3, 0)
    led.plot(3, 1)
    led.plot(0, 3)
    led.plot(1, 4)
    led.plot(2, 4)
    led.plot(3, 4)
    led.plot(4, 3)
}
function _1 () {
    led.plot(0, 0)
    led.plot(0, 1)
    led.plot(1, 0)
    led.plot(1, 1)
    led.plot(4, 0)
    led.plot(4, 1)
    led.plot(3, 0)
    led.plot(3, 1)
    led.plot(0, 3)
    led.plot(1, 3)
    led.plot(2, 3)
    led.plot(3, 3)
    led.plot(4, 3)
}
let slag = 0
slag = 467.75
basic.forever(function () {
	
})
